# Copyright 2015-2022 Data2ML. All Rights Reserved
#
# All intellectual properties not limited to patents, trademarks, industrial designs,
# copyrights, know-how including layout of images and contents contained herein
# belong to 'Data2Ml'. Any reproduction, modification, distribution
# or republishing materials without prior written consent is prohibited.
# for more please visit: http://data2ml.com.au 
#
# Author: Mohammad Nuruzzaman 
# Date: 4th Mar 2020

##########################################################
# Common configuration shared between all applications
##########################################################
configserver:
  name: Docker Registry Service
  status: Connected to the Registry Service running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Njc1Nzk3Nzg4ZDVmODBiNjA2NTA4MTU1YTMyYjk5ODY1Y2M5NWQ0NTRlMWQ2NDU5NjZjNjA4Y2YwMjhhMDExM2VhYWM0NzgzODZlMTUzYzJhYmY5Y2UxNWEwMTE3YzE0MjU0YmZhZGQyNmE3MjQ4YzgxZDIxZTI3NDg4N2U4YWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
